### ISSUE TITLE
Show Sidebar Disabled

### ISSUE THREAD

**Issue by cliftonlabrum** [Dis3buted/SplitViewController#2]
Thanks for creating this example. When I try to replicate it in a new Xcode project, "Show Sidebar" in the "View" menu is disabled. I've tried to do everything you did in your example.

Can you take a look at this sample project and tell me why it won't work? I'm trying to make the right pane show/hide.

Thanks!
[SidebarTest.zip](https://github.com/Dis3buted/SplitViewController/files/1431912/SidebarTest.zip)

**Comment by Dis3buted** [comment]
Okay I will do it during weekend


Mvh: Peter


( ͡° ͜ʖ ͡°)   ¯\_(ツ)_/¯




________________________________

**Comment by Dis3buted** [comment]
Missing connection to toggleSidebar

**Comment by cliftonlabrum** [comment]
Thanks!
